Repository site15/site15.ru, pull requests merged in 2023-02, with the labels that each got.

#45 feat: append support optional searching by any fields in content-type when we tried get many
  apps/server/src/app/contact-type/contact-type.controller.ts
  apps/server/src/app/contact-type/contact-type.service.ts
  apps/server/src/app/contact-type/dto/search-contact-type-query.dto.ts
Labels: release

#44 feat: add ngx-dynamic-form-builder and change work with forms to it #47
  apps/client/project.json
  apps/client/src/app/app.component.html
  apps/client/src/app/app.module.ts
  apps/client/src/app/contact-type/components/contact-type-details/contact-type-details.component.html
  apps/client/src/app/contact-type/components/contact-type-details/contact-type-details.component.ts
  apps/client/src/app/contact-type/components/contact-type-list/contact-type-list.component.html
  apps/client/src/app/contact-type/components/contact-type-list/contact-type-list.component.scss
  apps/client/src/app/contact-type/components/contact-type-list/contact-type-list.component.ts
  apps/client/src/app/contact-type/contact-type.module.ts
  apps/client/src/app/contact-type/contact-type.service.ts
  apps/client/src/app/shared/models/contact-type.model.ts
  apps/client/src/app/shared/modules/backend-error/backend-error.module.ts
  apps/client/src/app/shared/modules/backend-error/components/backend-error/backend-error.component.ts
  apps/client/src/app/shared/modules/backend-error/pipes/get-error-by-param.pipe.ts
  apps/client/src/app/shared/modules/prompt/components/prompt/prompt.component.html
  apps/client/src/app/shared/modules/prompt/components/prompt/prompt.component.scss
  apps/client/src/app/shared/modules/prompt/components/prompt/prompt.component.ts
  apps/client/src/app/shared/modules/prompt/interface/prompt-options.interface.ts
  apps/client/src/app/shared/modules/prompt/prompt.module.ts
  apps/client/src/app/shared/modules/prompt/prompt.service.ts
  apps/client/src/styles.scss
  devops/docker/prod/docker-compose-build-server-base-image.sh
  devops/set-env.sh
  package-lock.json
  package.json
Labels: client

#43 feat: rename all database tables from snake case to camel case
  apps/server/src/app/app.controller.ts
  apps/server/src/app/contact-type/contact-type.service.ts
  apps/server/src/app/contact-type/dto/contact-type.dto.ts
  apps/server/src/app/contact-type/interfaces/contact-type.interface.ts
  migrations/V202301120345__Transform_snake_case_to_camel_case.pgsql
  prisma/schema.prisma
Labels: release, next
